# Generated by Django 3.0.7 on 2020-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('CountryCode', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=100)),
                ('CityCode', models.CharField(max_length=100)),
                ('Lat', models.IntegerField()),
                ('Lon', models.IntegerField()),
                ('Confirmed', models.IntegerField()),
                ('Deaths', models.IntegerField()),
                ('Recovered', models.IntegerField()),
                ('Active', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
